version: '3.9'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/code/
    depends_on:
      - redis_cache
      - rabbitmq
    networks:
      - backend

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6380:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

volumes:
  rabbitmq_data:

networks:
  backend:
    external: true
